## Categorical Handling
(Label Encoding & One Hot Encoding)

1. Categorical Encoding: proses mengkonversi niali kategorical menjadi nilai numerical 
2. jenisnya ada banyak tapi populer ada 2, yaitu: Label encoding dan One hot encoding (referensi: https:// -en.wikipedia.org/wiki/one-hot)
3. Di label encoding setiap kategori feature akan diurutkan secara alfabet dan digambarkan dengan nilai integer
4. di one hot encoding kategori feature akan diurutkan secraa alfabet dan digambarkan sbgai sekumpulan bits

## Label Encoding

In [ ]:
# Buat dataet
import pandas as pd

df = pd.DataFrame({
    'country':['India', 'US', 'Japan', 'US', 'Japan'],
    'age':[44, 34, 46, 35, 23],
    'salary':[72000, 65000, 98000, 45000, 34000]
})
df

  country  age  salary
0   India   44   72000
1      US   34   65000
2   Japan   46   98000
3      US   35   45000
4   Japan   23   34000

## Label Encoding pada Scikit Learn

In [2]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['country'] = label_encoder.fit_transform(df['country'])
df

   country  age  salary
0        0   44   72000
1        2   34   65000
2        1   46   98000
3        2   35   45000
4        1   23   34000

In [3]:
label_encoder.classes_

array(['India', 'Japan', 'US'], dtype=object)

## One Hot Encoding

In [28]:
# Buat dataet
import pandas as pd

df = pd.DataFrame({
    'country':['Indonesia', 'UK', 'Jepang', 'UK', 'Jepang'],
    'age':[44, 34, 46, 35, 23],
    'salary':[72000, 65000, 98000, 45000, 34000]
})
df

     country  age  salary
0  Indonesia   44   72000
1         UK   34   65000
2     Jepang   46   98000
3         UK   35   45000
4     Jepang   23   34000

## One Hot encoding pada scikit learn

In [12]:
from sklearn.preprocessing import OneHotEncoder
x = df['country'].values.reshape(-1, 1)
x

array([['Indonesia'],
       ['UK'],
       ['Jepang'],
       ['UK'],
       ['Jepang']], dtype=object)

In [13]:
oneshot_encoder = OneHotEncoder()
x = oneshot_encoder.fit_transform(x).toarray()
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [14]:
oneshot_encoder.categories_

[array(['Indonesia', 'Jepang', 'UK'], dtype=object)]

In [16]:
df_onehot = pd.DataFrame(x, columns=[str(i) for i in range(x.shape[1])])
df_onehot

     0    1    2
0  1.0  0.0  0.0
1  0.0  0.0  1.0
2  0.0  1.0  0.0
3  0.0  0.0  1.0
4  0.0  1.0  0.0

In [29]:
df = pd.concat([df_onehot, df], axis=1)
df

     0    1    2    country  age  salary
0  1.0  0.0  0.0  Indonesia   44   72000
1  0.0  0.0  1.0         UK   34   65000
2  0.0  1.0  0.0     Jepang   46   98000
3  0.0  0.0  1.0         UK   35   45000
4  0.0  1.0  0.0     Jepang   23   34000

In [30]:
df = df.drop(['country'], axis=1)
df

     0    1    2  age  salary
0  1.0  0.0  0.0   44   72000
1  0.0  0.0  1.0   34   65000
2  0.0  1.0  0.0   46   98000
3  0.0  0.0  1.0   35   45000
4  0.0  1.0  0.0   23   34000

## Notes: Label Encoding vs One Hot Encoding
Kita menerapkan One Hot Encoding bila:

- Nilai categorical adalah nominal
- Jumlah kategori yang ada tidak terlalu banyak

Kita menerapkan Label Encoding bila:

- Nilai categorical adalah ordinal
- Jumlah kategori yang ada relatif banyak