In [5]:
# Belajar Pandas dr 0 Indonesia Belajar (Pandas 01 | Menyertakan Prefix dan Suffix pada seluruh Kolom Pandas Data Frame | Python Pandas)
import pandas as pd
import numpy as np
import os
os.system('cls')

#print(pd.__version__) # Mau ngecek versi berapa pandas dan numpy yang kita gunakan
#print(np.__version__)

n_rows = 5 # membuat 5 baris 
n_cols = 5 # membuat 5 kolom
cols = tuple('ABCDE') # kolomnya tuple yang diberi label abcde

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)),columns=cols)
print(df)
#tuple('ABCDE') # gunanya tuple supaya elemen nya di ""
# membuat prefikx kolom
df.add_prefix('kolom_') #bisa diganti ke baris juga 
# membuat suffix kolom
df.add_suffix('_field')

   A  B  C  D  E
0  8  1  5  2  3
1  1  3  5  2  4
2  4  8  2  2  4
3  4  7  9  3  7
4  5  7  1  9  7

   A_field  B_field  C_field  D_field  E_field
0        8        1        5        2        3
1        1        3        5        2        4
2        4        8        2        2        4
3        4        7        9        3        7
4        5        7        1        9        7

In [ ]:
# Pandas 02 | Pemilihan baris (rows selection) pada Data Frame | Python Pandas | Data Science
# membuat persiapan dataframe
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')
df = pd.DataFrame(np.random.randint(1, 5, size=(n_rows, n_cols)), columns=cols)
df.add_prefix('kolom_') # oh gua baru ngeh bedanya pre and suffix depan belakang
# selection dengan operator logika '|' nah itu pengandaian or 
df[(df['A'] == 1) | (df['A'] == 3)] #hanya memilih kolom a bernilai 1 atau 3 lalu ditampilkan secara baris
# selection dengan fungsi isin(), ini untuk menggantikan fungsi yang sebelumnya |
df[df['A'].isin([1, 3])]
# mengenal operator negasi ~, yang tidak sama dengan 1 atau 3
df[~df['A'].isin([1, 3])]

   A  B  C  D  E
3  1  3  1  3  2
4  3  4  1  3  2

In [9]:
# Pandas 03 | Konversi tipe data String ke Numerik pada kolom Data Frame | Python Pandas
import pandas as pd
import numpy as np
# 1. Membuat data frame
dataFrame = {'col1':['1','2','3', 'teks'],
             'col2':['1','2','3','4']}
df=pd.DataFrame(dataFrame)
df
#df.dtypes # tipe data object
# konversi tipe data dengan fungsi astype()
df_x = df.astype({'col2':'float'})
df_x.dtypes # baris 2 berubah menjadi int
# konversi tipe data numerik dengan fungsi to_numerik()
df.apply(pd.to_numeric, errors='coerce') # teks akan berubah NaN/missing value

   col1  col2
0   1.0     1
1   2.0     2
2   3.0     3
3   NaN     4

In [29]:
# Pandas 04 | Pemilihan kolom (columns selection) pada Pandas Data Frame berdasarkan tipe data
import pandas as pd
import numpy as np
# 1. Membuat dataframe
n_rows = 5
n_cols = 2
cols= ['bilPecahan', 'bilBulat']
df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)),
                columns=cols)
df['bilPecahan'] = df['bilPecahan'].astype('float')
df.index = pd.date_range('2028-05-10',periods=n_rows, freq='H')
df = df.reset_index()
df['teks'] = list('ABCDE')
# 2. memilih kolom bertipe data numerik
df.select_dtypes(include='number')
df.select_dtypes(include='float')
df.select_dtypes(include='int')
# 3. Memilih kolom tipe data string / object
df.select_dtypes(include='object')
# 4. Memilih kolom tipe data datetime
df.select_dtypes(include='datetime')
# 5. Memilih kolom tipe data kombinasi
df.select_dtypes(include=['number','object'])

C:\Users\Louis Immanuel A\AppData\Local\Temp\ipykernel_45340\1352015588.py:11: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df.index = pd.date_range('2028-05-10',periods=n_rows, freq='H')

   bilPecahan  bilBulat teks
0        10.0         6    A
1         8.0         7    B
2        14.0        14    C
3         2.0        13    D
4        18.0        13    E

In [ ]:
# Pandas 05 | Membalik urutan baris dan kolom pada Data Frame | Python Pandas | Data Science
import pandas as pd
import numpy as np
# 1. membuat data frame
baris = 5
kolom = 5
isikolom = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(baris, kolom)), 
                  columns=isikolom)
# 2. membalik urutan kolom
df.loc[:, ::-1]
# 3. membalik urutan baris
df.loc[::-1]
# 4. membalik urutan baris dan melakukan penyesuaian ulang index
df.loc[::-1].reset_index(drop=True)

   E  D  C  B  A
0  4  8  2  5  9
1  9  3  4  1  1
2  4  1  6  3  3
3  7  3  7  5  1
4  8  7  1  6  8

In [39]:
# Pandas 06 | Mengganti nama kolom pada Data Frame | Python Pandas | Belajar Data Science | Indonesia
import pandas as pd 
import numpy as np 
# 1. membuat data frame
baris = 5
kolom = 5
isikolom = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(baris, kolom)), 
                  columns=isikolom)
# 2. Mengganti nama label kolom untuk DataFrame
df.rename(columns={'C':'Hobi'})
# 3. Mengganti nama label untuk banyak kolom DataFrame
df.rename(columns={'C':'Hobi', 'A':'ayam', 'D':'domba'})

   ayam  B  Hobi  domba  E
0     1  3     2      4  4
1     2  1     3      1  4
2     8  5     4      7  4
3     1  8     3      5  6
4     2  4     5      2  5

In [ ]:
# Pandas 07 | Menghapus (drop)missing values pada Data Frame | Python Pandas | Belajar Data Science
import pandas as pd 
import numpy as np 

baris = 30
kolom = 4
isiKolom = ['A', 'B', 'C', 'D']
df = pd.DataFrame(np.random.randn(baris, kolom), columns=isiKolom)
nan_mask = np.random.rand(baris, kolom) < 0.2
df[nan_mask] = np.nan

df = df.reset_index()
df.head()

df = df.rename(columns={'index':'Z'})
df.head()

df_backup = df.copy(deep=True)
# 2. menghapus setiap kolom yang mengandung missing values
#df = df.dropna(axis='columns')
#df.head() # yang tampil hanya yang tidak mengandung missing values
## 3. Menghapus (drop) setiap kolom yang mengandung missing values
#df = df.dropna(axis='columns')
#df.head()
## 4. menghapus setiap baris yang mengandung missing values 
#df = df_backup.copy(deep=True)
#df = df.dropna(axis='rows')
#df.head()
# katanya ada 2 pendekatan: menghapus kolom yang mengandung missing Values atau Baris yang mengandung
# 5. Persentase missing values untuk setiap kolom
df = df_backup.copy(deep=True)
df.isna().mean()
# 6. Menghapus(drop)setiap kolom yang mengandung missing values berdasarkan threshold
# ==> jadi ini kalau persentase yang bagus nya masih tertentu (disini make standar 90%) kalau yang dibawah itu dia bakal di hapus
treshold = len(df) * 0.9
df = df.dropna(thresh=treshold, axis='columns')
df.head()

   index         A         B         C         D
0      0  0.849995  1.308288 -1.800775 -0.975020
1      1 -1.940449  1.237902  0.117489 -0.274972
2      2  0.396586       NaN  1.427988  0.550229
3      3  1.030803  0.868907 -1.756811 -1.027021
4      4       NaN  0.175512 -0.844671 -0.670630

In [ ]:
# Pandas 08 | Memeriksa kesamaan antar kolom (Series) pada Data Frame | Python Pandas | Data Science
import pandas as pd
import numpy as np
# 1 buat data frame
data = {'A':[15, 15, 18, np.nan, 12],
        'B':[15, 15, 18, np.nan, 12]}
df = pd.DataFrame(data)
df
# sebuah frame terdiri dari kumpulan series
# 2. memeriksa kesamaan dengan operator dengan ==
df['A'] == df['B']
# 3. memeriksa kesamaan dengan method equals()
df['A'].equals(df['B'])
# ==> '==' tidak bisa memeriksa NaN lebih baik menggunakan equals

      A     B
0  15.0  15.0
1  15.0  15.0
2  18.0  18.0
3   NaN   NaN
4  12.0  12.0

In [ ]:
# Pandas 09 | Membagi Data Frame menjadi dua secara acak | Python Pandas | Belajar Data Science
import pandas as pd
import numpy as np
# 1. membuat data frame
baris = 10
kolom = 5
isikolom = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(baris, kolom)), 
                  columns=isikolom)
# 2. membagi data frame menjadi 2 secara acak berdasarkan proporsi tertentu
proporsi = 0.7
df_1 = df.sample(frac=proporsi)
df_2 =df.drop(df_1.index)
print(f'df_1 shape:\n{df_1.shape}\n')
print(f'df_2 shape:\n{df_2.shape}')
df_1
df_2

df_1 shape:
(7, 5)

df_2 shape:
(3, 5)

    A   B   C   D   E
2  13  12   2   8   3
5  13  17   1   4   9
6  11  18  17   8   3
4   5   2   8   4  18
9  15  19  12  13  14
1  13  19  17  10  12
0   4  11  14   2   1

In [20]:
# Pandas 10 | Mengganti nama kolom pada Data Frame berdasarkan pola | Python Pandas | Data Science
# 1. Mengimport dataframe
df = pd.read_csv(r'C:\Users\Louis Immanuel A\Downloads\titanicfull.csv')
df.columns = ['Pclass', 'Survival status', 'full Name', 'Sex', 'Age', 'Sib SP', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
df_backup = df.copy(deep=True)
# 2. Menggunakan lowercase untuk nama kolom dan mengg1anti spasi dengan _
df.columns = df.columns.str.replace(' ', '_').str.lower()
# 3. Memangkas kelebihan spasi pada nama kolom
df = df_backup.copy(deep=True)
df.columns=df.columns.str.lower().str.strip().str.replace(' ', '_')
df.head()

,pclass,survival_status,full_name,sex,age,sib_sp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

In [ ]:
# Pandas 11 | Seleksi kolom dan baris pada Data Frame menggunakan loc | Python Pandas | Data Science
# 1. Membuat Data Frame
baris = 10
kolom = 5
isikolom = tuple('ABCDE')
df = pd.DataFrame(np.random.randint(1, 20, size=(baris, kolom)), 
                  columns=isikolom)
# 2. Seleksi kolom dan baris menggunakan loc
df.loc[[0, 3, 4], ['B', 'E']]
# ==> loc terbagi menjadi 2 bagian besar yang satu untuk mengatur baris dan 1 lagi kolom
# 3. Seleksi baris dengan kondisi
df.loc[df['B']>10, ['B', 'D', 'E']]
# 4. Slicing Data Frame dengan loc
df.loc[0:4, 'B':'D']
# ==> slicing di loc angka ke dua(kalo disini 4) ikut masuk juga

    B   D   E
2  15   2   8
3  17   4   8
5  14  13   6
6  14   3  15
7  12  11  10
9  17  12   9

In [ ]:
# Pandas 12 | Membentuk kolom bertipe datetime dari beberapa kolom lain pada Pandas Data Frame
import pandas as pd
# 1. dataframe
data = {'day':[1, 2, 10, 25, 12],
        'month':[1, 2, 4, 5, 6],
        'year':[2000, 2001, 2010, 2015, 2020]}
df = pd.DataFrame(data)
print(df)
# 2. Membentuk kolom bertipe datetime
df['Penanggalan'] = pd.to_datetime(df[['day','month','year']])
df.dtypes

   day  month  year
0    1      1  2000
1    2      2  2001
2   10      4  2010
3   25      5  2015
4   12      6  2020

   day  month  year Penanggalan
0    1      1  2000  2000-01-01
1    2      2  2001  2001-02-02
2   10      4  2010  2010-04-10
3   25      5  2015  2015-05-25
4   12      6  2020  2020-06-12

In [5]:
# Pandas 13 | Konversi nilai numerik ke dalam kategori pada Data Frame | Python Pandas | Data Science
import pandas as pd
import numpy as np
# 1. Membuat Data Frame
baris = 10
kolom = 1
isikolom = ('usia',)
df = pd.DataFrame(np.random.randint(1, 99, size=(baris, kolom)), 
                  columns=isikolom)
df
# 2. Pengelompokan nilai numerik ke dalam beberapa kategori menggunakan cut()
df['kelompok_usia'] = pd.cut(df['usia'],
                             bins = [0, 18, 65, 99],
                             labels = ['anak-anak', 'dewasa', 'manula'])
df

   usia kelompok_usia
0    94        manula
1    90        manula
2    13     anak-anak
3    28        dewasa
4    77        manula
5    13     anak-anak
6    84        manula
7     7     anak-anak
8    88        manula
9    48        dewasa

In [ ]:
# Pandas 14 | Menggabungkan dua Pandas Data Frame | Python Pandas | Belajar Data Science | Indonesia
import pandas as pd
import numpy as np 
# 1. Membuat Data Frame
baris = 5
kolom = 5
isikolom = tuple('ABCDE')
df = pd.DataFrame(np.random.randint(1, 20, size=(baris, kolom)), 
                  columns=isikolom)
df1 = df.copy(deep=True)
df1 = df1.drop([1, 4])
df2 = df.copy(deep=True)
df2 = df2.drop([0, 3])
# 2. Menggabungkan dua data frame dengan 2 cara
df_inner = pd.merge(df1, df2, how='inner') # baris yang diambil hanya baris yang sama 
df_outer = pd.merge(df1, df2, how='outer') # baris yang diambil semua baris kecuali yang duplikat
df_outer

    A   B   C   D   E
0   1  10  14   8   1
1  11  13  18   3  16
2  14   3  10  16  13
3  19   8  18   3   6
4  19  15   9  18  18

In [4]:
# Pandas 15 | Memecah nilai string suatu kolom ke dalam beberapa kolom baru pada Pandas Data Frame
import pandas as pd
# 1. Membuat Data Frame
data = {'nama': ['Didi gas', 'dalang sumbing', 'mbah penunggu'],
        'tempat kelahiran': ['surakarta, jawa tengah', 'jakarta, DKI jakarta', 'Mojokerto, Jawa Tengah']}
df = pd.DataFrame(data)

# 2. Memecah nama depan dan nama belakang
df[['nama depan', 'nama belakang']] = df['nama'].str.split(' ', expand=True)
df[['kota', 'provinsi']] = df['tempat kelahiran'].str.split(',', expand=True)
df

,nama,tempat kelahiran,nama depan,nama belakang,kota,provinsi
0,Didi gas,"surakarta, jawa tengah",Didi,gas,surakarta,jawa tengah
1,dalang sumbing,"jakarta, DKI jakarta",dalang,sumbing,jakarta,DKI jakarta
2,mbah penunggu,"Mojokerto, Jawa Tengah",mbah,penunggu,Mojokerto,Jawa Tengah

In [ ]:
# Pandas 16 | Menata ulang Data Frame dengan multiple indexes menggunakan unstack | Data Science
import pandas as pd
# 1. Import dataframe
df = pd.read_csv(r'C:\Users\Louis Immanuel A\Downloads\titanicfull.csv')
df.head()
# 2. data frame dengan multiple indexes dari hasil grouping
df.groupby(['sex', 'pclass'])['survived'].mean().to_frame()
# 3. menata ulang data frame dengan mutiple indexes
df.groupby(['sex', 'pclass'])['survived'].mean().unstack()

pclass         1         2         3
sex
female  0.965278  0.886792  0.490741
male    0.340782  0.146199  0.152130

In [20]:
# Pandas 17 | Resampling pada data deret waktu | time series data | Belajar Data Science | Indonesia
import pandas as pd
import numpy as np

# 1. data frame
baris = 365 * 24
kolom = 2
isikolom = ['col1', 'col2']
df = pd.DataFrame(np.random.randint(1, 20, size=(baris, kolom)), 
                  columns=isikolom)
df.index = pd.date_range(start='2023-01-01', periods=baris, freq='h')
# 2. resampling data dengan interval monthly
df.resample('M')['col1'].sum().to_frame()
# 3. Resampling data dengan interval daily
df.resample('D')['col1'].sum().to_frame()

C:\Users\Louis Immanuel A\AppData\Local\Temp\ipykernel_36972\1417027538.py:13: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M')['col1'].sum().to_frame()

            col1
2023-01-01   242
2023-01-02   230
2023-01-03   243
2023-01-04   247
2023-01-05   239
...          ...
2023-12-27   233
2023-12-28   227
2023-12-29   275
2023-12-30   267
2023-12-31   257

[365 rows x 1 columns]

In [ ]:
# Pandas 18 | Membentuk dummy Data Frame | Python Pandas | Data Science | Bahasa Indonesia
import pandas as pd
import numpy as np
# 1. data frame
pd.DataFrame({'col1':[1, 2, 3, 4], 
              'col2':[5, 6, 7, 8]})
# 2. Membentuk Data Frame dari Numpy Array
n_rows = 5
n_cols = 3

arr = np.random.randint(1, 20, size=(n_rows, n_cols))
arr
pd.DataFrame(arr, columns=tuple('ABC'))
# 3. Membentuk Data Frame dengan memanfaatkan pandas.util.testing
# ada 3 jenis
n_rows = 30 
n_cols = 4 
columns = list('ABCD')
data = np.random.randn(n_rows, n_cols)
df = pd.DataFrame(data, columns=columns)
print(df.head())

n_rows = 5 
data = {
    'A': np.random.randn(n_rows),                 
    'B': np.arange(1, n_rows + 1),                
    'C': pd.date_range('2024-01-01', periods=n_rows), 
    'D': ['foo', 'bar', 'baz', 'qux', 'quux']    
}
df = pd.DataFrame(data)
print(df.head())

n_rows = 30  
n_cols = 4   
columns = list('ABCD')  
time_index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')  
df = pd.DataFrame(np.random.randn(n_rows, n_cols), index=time_index, columns=columns)
print(df.head())

n_rows = 5
n_cols = 4
data = np.random.randn(n_rows, n_cols)
df = pd.DataFrame(data, columns=list('ABCD'))
df.iloc[0, 1] = np.nan
df.iloc[2, 3] = np.nan
df.iloc[4, 0] = np.nan
print(df.head())

In [ ]:
# Pandas 19 | Formatting tampilan Data Frame | Python Pandas | Data Science | Bahasa Indonesia
import pandas as pd
import numpy as np
# 1. Data Frame
n_rows = 5
n_cols = 2
cols = ['omset', 'operasional']
df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df
# mengalikan antara kolom omset dan operasional dengan nilai
df['omset'] = df['omset'] * 100_000
df['operasional'] = df['operasional'] * 10_000
df # membuat kayak dataframenya menjadi styler ,jangan disamakan
# masih membuat dataframe
n_rows = 365  
df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, 2)), columns=['col1', 'col2'])
df.index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')
df = df.reset_index().rename(columns={'index': 'tanggal'})
print(df)

# 2. Melakukan formatting tampilan Data Frame
formatku = {'tanggal':'{:%d/%m/%y}', 
            'operasional':'Rp {:.2f}',
            'omset':'Rp {:.2f}'}
laporan = df.style.format(formatku)
laporan
type(laporan)
laporan.set_caption('Data Omset dan Operasional') # ini kayak bikin judul diatas

In [7]:
# Pandas 20 | Menggabungkan dua Data Frame secara berdampingan | Python Pandas | Data Science
import pandas as pd
# 1. Membuat data frame (bikin 2)
d1 = {'col1':[1, 2, 3], 
      'col2':[10, 20, 30]}
df1 = pd.DataFrame(d1)
d2 = {'col3':[4, 5, 6], 
      'col4':[40, 50, 60]}
df2 = pd.DataFrame(d2)
# 2. Menggabungkan (merge) dua Data Frame secara berdampingan
df = pd.merge(df1, df2, left_index=True, right_index=True)
df
# kalau yang tadi kan ada yang sama atau semuanya nah yang ini dibikin berdampingan

   col1  col2  col3  col4
0     1    10     4    40
1     2    20     5    50
2     3    30     6    60

In [ ]:
# Pandas 21 | Agregasi pada Pandas Data Frame dengan agg | Python Pandas | Belajar Data Science
import pandas as pd

# 1. Import DataFrame
df = pd.read_csv(r"C:\Users\Louis Immanuel A\Downloads\Iris.csv")
df.head()
# 2. Mengenal groupby() dan fungsi agregasi (agregasi itu untuk fungsi dengan banyak kelompok)
df.groupby('Species')['PetalLengthCm'].count().to_frame()
df.groupby('Species')['PetalLengthCm'].mean().to_frame()
df.groupby('Species')['PetalLengthCm'].median().to_frame()
# 3. Agregasi dengan agg()
df.groupby('Species')['PetalLengthCm'].agg(['count', 'mean', 'median'])
# 4. Agregasi dengan describe()
df.groupby('Species')['PetalLengthCm'].describe()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
# Pandas 22 | Memantau penggunaan memory pada Data Frame | Python Pandas | Belajar Data Science
import pandas as pd
# 1. Import dataframe
df_titanic = pd.read_csv(r"C:\Users\Louis Immanuel A\Downloads\titanicfull.csv")
df_iris = pd.read_csv(r"C:\Users\Louis Immanuel A\Downloads\Iris.csv")
# 2. Memantau penggunaan memory untuk setiap kolom dari suatu Data Frame
df_titanic.memory_usage(deep=True)
df_iris.memory_usage(deep=True)

In [ ]:
# Pandas 23 | Seleksi baris pada Data Frame dengan query | Python Pandas | Belajar Data Science
# 1. Membuat dataframe
d = {'kolom_satu':[1, 2, 3, 4, 5], 
     'kolom dua':[10, 20, 30, 40, 50]}
df = pd.DataFrame(d)
# 2. Seleksi baris dengan query()
df.query('kolom_satu > 2') #harus ditulis string
df.query('`kolom dua` > 30') #kalau ada spasi pakai ``

In [ ]:
# Pandas 24 | UTC dan konversi zona waktu pada Python Pandas | time zone | Belajar Data Science
import pandas as pd
# 1. Membuat series
s = pd.Series(range(1591683521, 1592201921, 3600))
s = pd.to_datetime(s, unit='s')
# merepresentasikan unik epoch time, epoch time converter, detik
# 2. Pengaturan zona waktu (time zone)
s = s.dt.tz_localize('UTC')
s = s.dt.tz_convert('Asia/Jakarta')
s = s.dt.tz_convert('Australia/Hobart')

In [ ]:
# Pandas 25 | Pengaturan tampilan pada Python Pandas | display option | Belajar Data Science
# 1. mengimpor data
df = pd.read_csv(r"C:\Users\Louis Immanuel A\Downloads\titanicfull.csv")
# 2. Pengaturan tampilan
pd.set_option('display.max_rows', 5)
pd.set_option('display.max_columns', 6)
pd.set_option('display.max_colwidth', 20)
pd.reset_option('^display.', silent=True)
pd.describe_option()

In [ ]:
# Pandas 26 | Membuat Data Frame dari hasil seleksi Spreadsheet | Python Pandas | Belajar Data Science
import pandas as pd
df = pd.read_clipboard()
# ==> semisal adaa spretshet lu salin habis itu lu run syntax ini

In [ ]:
# Pandas 27 | Fungsi agregasi first dan last pada Python Pandas | Data Science | Bahasa Indonesia
# 1. Membuat dataframe
d = {'dokter':['Budi', 'Wati', 'Iwan', 'Budi', 'Budi', 'Wati'], 
     'pasien':['Abdul', 'Rahmat', 'Asep', 'Joko', 'Wiwin', 'Lisa']}
df = pd.DataFrame(d)
# 2. Mengenal fungsi agregasi first() dan last()
df.groupby('dokter')['pasien'].count().to_frame()
df
df.groupby('dokter')['pasien'].first().to_frame()
df
df.groupby('dokter')['pasien'].last().to_frame()
df
# ==> cobain aja ada berapa total pasien, pasien pertama, terakhir masing masing pasien

NameError: name 'pd' is not defined

In [ ]:
# Pandas 28 | Mengenal explode dan implode List pada Pandas Data Frame | Python Pandas | Data Science
# 1. Dataframe
d = {'Team':['DC', 'Marvel'], 
     'Heroes':[['Batman', 'Superman', 'Wonder Woman', 'Aquaman', 'Green Lantern', 'Shazam'], 
               ['Iron Man', 'Captain America', 'Ant-Man', 'Black Panther', 'Captain Marvel']]}
df = pd.DataFrame(d)
df
# 2. explode
df1 = df.explode('Heroes')
df1
# ==> supaya kalau diprint bersatu kayak list menjadi terpisah
# 3. Implode
d = {'Team':['DC', 'Marvel']}
df2 = pd.DataFrame(d)
df2
df2['Imploded'] = df1.groupby(df1.index)['Heroes'].agg(list)
df2
# ==> ini kebalikannya

In [ ]:
# Pandas 29 | Random Sampling pada Pandas Data Frame | Python Pandas | Belajar Data Science
# 1. Membuat data frame
import pandas as pd
d = {'col_1':[1, 2, 3, 4, 5], 
     'col_2':[10, 20, 30, 40, 50]}
df = pd.DataFrame(d)
df
# 2. Random sampling with/without replacement
df.sample(n=4, replace=False, random_state=0) # n jumlah data, replace supaya data masuk lagi, randomstate bebas
df.sample(n=4, replace=True, random_state=0)
# kayak membuat data frame tapi dengan mengambil data secara acak

In [ ]:
# Pandas 30 | Akses nilai variabel dalam fungsi query | Pandas Data Frame | Belajar Data Science
import pandas as pd
import numpy as np
# 1. membuat dataframe
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df
# 2. Akses nilai variabel pada query()
df.query('A > 10')
# seleksi baris dengan kondisi
rerata = df['A'].mean()
rerata
# seleksi per kolom yang sudah ditentukan
df.query('A > @rerata')
# ini penggabungan

In [ ]:
# Pandas 31 | Tipe data ordinal pada Pandas Data Frame | Python Pandas | Belajar Data Science
# 1. Membuat dataframe
d = {'pelanggan':[11, 12, 13, 14], 
     'kepuasan':['baik', 'cukup', 'buruk', 'cukup']}

df = pd.DataFrame(d)
df
# 2. Tipe data ordinal pada Pandas
from pandas.api.types import CategoricalDtype
tingkat_kepuasan = CategoricalDtype(['buruk', 'cukup', 'baik', 'sangat baik'], 
                                    ordered=True)
# categorical dtype ini buat mengajari komputer urutannya
df['kepuasan'] = df['kepuasan'].astype(tingkat_kepuasan)
df
df = df.sort_values('kepuasan', ascending=True)
df
df[df['kepuasan'] >= 'cukup']

In [ ]:
# andas 32 | Visualisasi Data - Pandas Data Frame | Plotting | Python Pandas | Belajar Data Science
# 1. membuat dataframe
n_rows = 40
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df.head()
# 2. Line Plot
df.head()
df.plot(kind='line')
# ini untuk semua
df[['A', 'B']].plot(kind='line')
# ini untuk yang khusus
# 3. Bar Plot
df.head()
df.plot(kind='bar')
df[['A', 'B']].plot(kind='bar')
df[['A', 'B']].head().plot(kind='bar')
df[['A', 'B']].head().plot(kind='barh')
# ini supaya barplotnya ke samping 
# 4. Area Plot
df.head()
df.plot(kind='area')
df[['A', 'B']].head().plot(kind='area')
# 5. Box Plot
df.head()
df.plot(kind='box')
# 6. Histogram
df.head()
df.plot(kind='hist')
df[['A', 'B']].plot(kind='hist')
# 7. Kernel Density Estimation (KDE)
df.head()
df.plot(kind='kde')
# 8. Scatter Plot
df.head()
df.plot(x='A', y='B', kind='scatter')

In [ ]:
# andas 33 | Nilai Kumulatif pada Pandas Data Frame | Python Pandas | Data Science | Bahasa Indonesia
# 1. Membuat dataframe
d = {'pemain':['Budi', 'Joni', 'Iwan', 'Budi', 'Budi', 'Iwan', 'Asep', 'Joni'], 
     'goal':[2, 1, 3, 1, 1, 2, 2, 3]}
df = pd.DataFrame(d)
df
# 2. Menampilkan nilai kumulatif (cummulative)
df['goal'].cumsum().to_frame()
df['jumlah_goal_kumulatif'] = df['goal'].cumsum()
df
df['jumlah_goal_kumulatif_tiap_pemain'] = df.groupby('pemain')['goal'].cumsum()
df
df['cummax'] = df['goal'].cummax()
df
df['cummin'] = df['goal'].cummin()
df
df['cumprod'] = df['goal'].cumprod()
df
# ini buat lihat nilai kumulatif, paling besar/kecil, trus hasil perkalian kumulatig

In [ ]:
# Pandas 34 | Mapping Data Frame dengan applymap | Python Pandas | Data Science | Bahasa Indonesia
# 1. Membuat dataframe
df = pd.DataFrame({'jenis_kelamin':['Pria', 'Wanita', 'lelaki', 'Lelaki', 'perempuan'], 
                   'usia':[23, 21, 24, 22, 21], 
                   'shift':['pagi', 'siang', 'Malam', 'Siang', 'pagi']})
df
# 2. Mapping pada Data Frame dengan applymap()
df = df.applymap(lambda x: x.lower() if type(x) == str else x)
df
# 3. applymap() dengan dictionary
mapping = {'pria':'L',
           'lelaki':'L',
           'wanita':'P',
           'perempuan':'P',
           'pagi':1,
           'siang':2,
           'malam':3}
# ini kayak membuat standarisasi semuanya semisal ada yang mau huruf besar/kecil semua
df.applymap(mapping.get)
df[['jenis_kelamin', 'shift']] = df[['jenis_kelamin', 'shift']].applymap(mapping.get)

df

In [ ]:
# Pandas 35 | Memadukan fungsi agregasi dengan transform | Python Pandas | Belajar Data Science
# 1. Membuat dataframe
d = {'no_nota':[1, 1, 1, 2, 2, 3, 4, 5], 
     'kopi': ['latte', 'cappuccino', 'espresso', 'latte', 'espresso', 'cappuccino', 'latte', 'espresso'],
     'harga':[50, 60, 80, 150, 120, 60, 100, 40]}

df = pd.DataFrame(d)
df
# 2. Menghitung total harga untuk tiap nomor nota
df.groupby('no_nota')['harga'].sum().to_frame()
df['total_harga'] = df.groupby('no_nota')['harga'].transform(sum)
df
# 3. Menghitung total omset untuk tiap jenis kopi yang terjual
df.groupby('kopi')['harga'].sum().to_frame()
df['total_omset'] = df.groupby('kopi')['harga'].transform(sum)
df

In [ ]:
# Pandas 36 | Menyatukan kolom pada Pandas Data Frame | Python Pandas | Belajar Data Science
# 1. Membuat dataframe
data = {'nama': ['bayu', 'indra', 'devi', 'agni'],
        'jenis_kelamin': ['L', 'L', 'P', 'L'], 
        'usia': [23, 21, 22, 25]}

df = pd.DataFrame(data)
df
# 2. Menyatukan kolom dengan str.cat()
df['nama'].str.cat(df['jenis_kelamin'], sep=', ').to_frame()
df['nama_jk'] = df['nama'].str.cat(df['jenis_kelamin'], sep=', ')
df

df['nama'].str.cat(df['usia'].astype('str'), sep=' - ').to_frame()
df['nama_usia'] = df['nama'].str.cat(df['usia'].astype('str'), sep=' - ')
df # nah yang ini itu 1 tipe string mau digabung dengan integer makanya pake astype dulu

In [ ]:
# Pandas 37 | Seleksi baris dengan banyak kriteria pada Data Frame | Python Pandas | Data Science
# 1. Import dataframe
df = pd.read_csv(r'C:\Users\Louis Immanuel A\Downloads\titanicfull.csv')
df.head()

# 2. Seleksi baris dengan banyak kriteria
df[(df['sex']=='female') & (df['age']>=60) & (df['embarked']=='S') & (df['survived']==1)]
df[
    (df['sex']=='female') & 
    (df['age']>=60) & 
    (df['embarked']=='S') & 
    (df['survived']==1)
]
kr1 = df['sex']=='female'
kr2 = df['age']>=60
kr3 = df['embarked']=='S'
kr4 = df['survived']==1

df[kr1 & kr2 & kr3 & kr4]
# intinya cuma beda craa penulisan doang

In [ ]:
# Pandas 38 | Parameter header dan skiprows pada read_csv | Python Pandas | Belajar Data Science
# 1. Persiapan Data Frame
df = pd.read_csv('./data/iris_error.csv') # ini kolom header atau label kacau malah ditengah
df.head(8)
df = pd.read_csv('./data/iris_error.csv', header=2, skiprows=[5,6])
df.head() # karena judulnya mulai di baris ke 2, dan baris ke 5 dan 6 itu error jadi di skip

In [ ]:
# Pandas 39 | Mengacak urutan baris pada Data Frame | Python Pandas | Belajar Data Science
import pandas as pd
import numpy as np
n_rows = 6
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 5, size=(n_rows, n_cols)), 
                  columns=cols)
df
# 2.Mengacak urutan baris pada DataFrame
df.sample(frac=1.0, random_state=1)
df.sample(frac=1.0, random_state=1).reset_index(drop=True) 
# reset index supaya walaupun di acak akan normal index nya

In [ ]:
#Pandas 40 | Akses sekelompok data pada Data Frame yang sudah terkelompok | Python Pandas | Indonesia
import pandas as pd
import numpy as np
# 1. import data
df = pd.read_csv(r'C:\Users\Louis Immanuel A\Downloads\titanicfull.csv')
df.head()
# 2. Mengakses sekelompok data yang sudah terkelompok dengan get_group()
grouped_df = df.groupby('sex')
grouped_df.get_group('female').head(10)
grouped_df = df.groupby('survived')
grouped_df.get_group(1).head(10)

In [ ]:
# Pandas 41 | Agregasi pada banyak kolom Data Frame dengan agg | Python Pandas | Data Science
# 1. import data
df = pd.read_csv(r'C:\Users\Louis Immanuel A\Downloads\titanicfull.csv')
df.head()
# 2. Menerapkan agregasi pada sejumlah kolom dengan agg()
df.groupby('pclass').agg({'pclass':'count', 
                          'age':['mean', 'max'], 
                          'survived': 'mean'})
df.groupby('pclass').agg(n_pass=('pclass', 'count'),
                         avg_age=('age', 'mean'),
                         max_age=('age', 'max'), 
                         survival_rate=('survived', 'mean'))
# lebih bagus yang cara penulisan kedua dia bikin nama kolom dipilih kolom mana dan fungsi apa saja

In [ ]:
# Pandas 42 | Mengurutkan data kolom pada Data Frame | Python Pandas | Belajar Data Science
# 1. Import dataframe
df = pd.read_csv(r'C:\Users\Louis Immanuel A\Downloads\titanicfull.csv')
df.head()
# 2. Mengurutkan data berdasarkan kolom tertentu
df.sort_values('age').head()
df.sort_values('age', ascending=False).head()
# false = besar ke kecil
df.sort_values(['survived', 'age']).head()

In [ ]:
# Pandas 43 | Menangani whitespace pada Pandas Data Frame | Python Pandas | Belajar Data Science
# 1. Buat dataframe
import pandas as pd
import numpy as np
data = {'nim': ['10', '11', '12', '13', '  '],
        'nama': ['adi', '  ', 'tejo', '  ', 'bejo']}
df = pd.DataFrame(data)
df
# 2. Menangani whitespace pada Data Frame
df
df.info()
df = df.replace(r'^\s*$', np.nan, regex=True)
df
df.info()
# nanti kalau spasi doang itu bakal kedetek nan atau missing value

In [ ]:
# Pandas 44 | Menata ulang kolom Data Frame | Python Pandas | Data Science | Bahasa Indonesia
# 1. Buat dataframe dulu
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')
df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df
# 2. Menata ulang penempatan kolom pada Data Frame
df[['D', 'C', 'A', 'E', 'B']]
df
df = df[['D', 'C', 'A', 'E', 'B']] # supaya inplace = true
df

In [ ]:
# Pandas 45 | Memadukan loc dan iloc untuk seleksi data pada Data Frame | Python Pandas | Data Science
# 1. Import dataframe
df = pd.read_csv(r'C:\Users\Louis Immanuel A\Downloads\titanicfull.csv')
df.head()
# 2. Memadukan loc dan iloc untuk melakukan seleksi data
df.iloc[15:20, :].loc[:, 'name':'age'] # loc & iloc = untuk melakukan seleksi berdasarkan baris dan kolom
df.loc[:, 'name':'age'].iloc[15:20, :] # intinya urutan pemanggilan mau loc atau iloc dulu